export const INDIAN_STATES = [
  { displayName: 'Andhra Pradesh', value: 'AP' },
  { displayName: 'Arunachal Pradesh', value: 'AR' },
  { displayName: 'Assam', value: 'AS' },
  { displayName: 'Bihar', value: 'BR' },
  { displayName: 'Chhattisgarh', value: 'CG' },
  { displayName: 'Goa', value: 'GA' },
  { displayName: 'Gujarat', value: 'GJ' },
  { displayName: 'Haryana', value: 'HR' },
  { displayName: 'Himachal Pradesh', value: 'HP' },
  { displayName: 'Jharkhand', value: 'JH' },
  { displayName: 'Karnataka', value: 'KA' },
  { displayName: 'Kerala', value: 'KL' },
  { displayName: 'Madhya Pradesh', value: 'MP' },
  { displayName: 'Maharashtra', value: 'MH' },
  { displayName: 'Manipur', value: 'MN' },
  { displayName: 'Meghalaya', value: 'ML' },
  { displayName: 'Mizoram', value: 'MZ' },
  { displayName: 'Nagaland', value: 'NL' },
  { displayName: 'Odisha', value: 'OR' },
  { displayName: 'Punjab', value: 'PB' },
  { displayName: 'Rajasthan', value: 'RJ' },
  { displayName: 'Sikkim', value: 'SK' },
  { displayName: 'Tamil Nadu', value: 'TN' },
  { displayName: 'Telangana', value: 'TG' },
  { displayName: 'Tripura', value: 'TR' },
  { displayName: 'Uttar Pradesh', value: 'UP' },
  { displayName: 'Uttarakhand', value: 'UT' },
  { displayName: 'West Bengal', value: 'WB' },
  { displayName: 'Delhi', value: 'DL' },
  { displayName: 'Jammu and Kashmir', value: 'JK' },
  { displayName: 'Ladakh', value: 'LA' },
  { displayName: 'Puducherry', value: 'PY' },
  { displayName: 'Chandigarh', value: 'CH' },
  { displayName: 'Andaman and Nicobar Islands', value: 'AN' },
  { displayName: 'Dadra and Nagar Haveli and Daman and Diu', value: 'DN' },
  { displayName: 'Lakshadweep', value: 'LD' }
] as const

export type IndianState = (typeof INDIAN_STATES)[number]
